# Generated by Django 3.2.3 on 2021-10-24 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('village', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Karnatak', 'karnatak'), ('Goa', 'goa'), ('Maharastra', 'maharastra')], default='', max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
