# Generated by Django 3.2.3 on 2021-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211024_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Karnatak', max_length=10),
        ),
    ]
