# Generated by Django 3.2.3 on 2021-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
